### ISSUE TITLE
Feeback of queries

### ISSUE THREAD

**Issue by clin99** [hobbit-project/DEBS-GC-2018#1]
Do we get feedback (like the correct destination and arrival time) for each query? 
If not, how does it relate to machine learning prediction?

**Comment by smirnp** [comment]
Data tuples are given to benchmarking systems sequentially, i.e. each new tuple is given after the previous one was processed and result (prediction) was returned to evaluation storage. 
So you can find feedback in next tuples, but cannot change returned predictions.

**Comment by tsung-wei-huang** [comment]
Thanks. Do we need to wait until Jan 15 for this to be online?

**Comment by smirnp** [comment]
Yes, the benchmark, helpful instructions and the test data set (for training models) will be available by the mid of Jan 2018.

**Comment by micheleporretta** [comment]
One question. The data set for training models will contain, for each tuple, the destination port and the corresponding travel time. Right?

**Comment by naqwert85** [comment]
Hi! Is the test data set available yet?

**Comment by smirnp** [comment]
Hi!

The dataset is already prepared, but some formal concerns still left to be solved.

Hopefully it will be released in couple of days.

**Comment by smirnp** [comment]
Please find the training dataset and "how-to-obtain" instructions here: www.cs.otago.ac.nz/debs2018/calls/gc.html.

The training dataset with calculated labels and corrected port's radiuses will be announced in the next couple of days.
