### ISSUE TITLE
Questions about the dataset

### ISSUE THREAD

**Issue by clin99** [hobbit-project/DEBS-GC-2018#10]
Hi, we have several questions about the dataset:

1. Will a tuple be sent (queried) more than once?
2. What is the maximum possible number of tasks to handle by our system?
3. In the provided training data, many tuples have the same *SHIP_ID* and *ARRIVAL_PORT*. As a result, the destination port is largely dependent on the *SHIP_ID*. Is this normal?
4. What is the maximum possible number of ships/SHIP_ID (unique ship)?
5. Will we know the range of every field?

Thanks.

**Comment by smirnp** [comment]
Hi! Here are the answers:
1. No.
2. According to the current data not higher than 1M. 
3. This is normal for each a single trip. But one ship may have several trips to different destination ports.
4. According to the current data not higher than 600 unique ships.
5. No. We consider solutions to be a prototypes of real systems, which will never get the finite stream to assess the ranges. 

Best regards.

**Comment by clin99** [comment]
Thanks for your answering. I still have some questions about the dataset.

1. For some fields such as longitude and latitude, should their values be between 0 and 360?    
If this is true, could you please point out the fields whose values are bounded and their ranges?

2. For the *TIMESTAMP* field, when is the earliest possible timestamp value?  Is this fixed or can we simply assume a very early time like 2000/1/1?

3. In the provided training dataset,  the *Reported_Draught* could be missing in some tuples. What fields could also have missing values?

4. In the provided training data, there is a file *ports.csv* listing all possible destination ports. Is this information also available when testing our system?   If yes, do we assume the information is always stored in a file called *ports.csv*?

5. For the data stream, I found different ships can send queries concurrently. When a ship receives a 
prediction, does it send next query immediately regardless of other ships or does it send next query 
until all ships get their predictions (synchronize with others)?

Thanks.

**Comment by smirnp** [comment]
@clin99, please find the answers:
1-3: Please find the corrected ranges in comments below.

4. The data labeling was done using the Ports.csv. Of course you can use the file in your system to get information about port coordinates and radiuses. The benchmark will send unlabeled tuples to the system.   

5. Data submission is sequential per single ship. But we have many ships (>500), which are serving in parallel. It means the at the moment we will have 500 tuples in the queue, even the system not yet returned any prediction.  Once the system returns the prediction – new tuple for that ship will be added to the queue.

**Comment by clin99** [comment]
@smirnp  Thanks for your answering. 

1. In the provided training dataset (_training_labeled.csv_), I found the maximum value of LAT is 44.42255 and the maximum value of LON is 36.13883. Could you please check the range of LAT and LON?

2. On the [official web page](http://www.cs.otago.ac.nz/debs2018/calls/gc.html), there is no ShipType in the schema, is this an error?

3. The [official web page](http://www.cs.otago.ac.nz/debs2018/calls/gc.html) says we can use the World Port Index (WPI) to get the information of all ports. But in the Ports.csv, there is a port "FOS SUR MER" that I didn't find in the WPI. Which one (WPI or Ports.csv) should we use to get the information of all ports?

4. What is the format of prediction? Is it a tuple that contains the <TaskID, ArrivalPort, ArrivalTime>?

5. Does the benchmark send the query and feedback of query over the same channel to the system?  If yes, how do we distinguish them?

**Comment by tsung-wei-huang** [comment]
@smirnp 

Does the following range hold true for all hidden testcases as well? Many learning algorithms require these ranges to be hard-coded.

ShipType: [0, 99],
Speed [0, 103],
LON: [-6, 30],
LAT [31, 42],
Course [0, 360],
Heading [0, 512] may be null,
Timestamp [10-03-15, 19-05-15]
DEPARTURE_PORT_NAME: see ports.csv
Reported_Draught: [20, 255] may be null,
ARRIVAL_CALC: same as Timestamp, may be null
ARRIVAL_PORT_CALC: see ports.csv, may be null

**Comment by smirnp** [comment]
@clin99 , 
1. thank you for comment. Please find the corrected ranges:
ShipType: [0, 99],
Speed [0, 103],
LON: [-6, 37],
LAT [32, 45],
Course [0, 360],
Heading [0, 511] may be null,
Timestamp [10-03-15, 19-05-15]
DEPARTURE_PORT_NAME: see ports.csv
Reported_Draught: [20, 255] may be null,
ARRIVAL_CALC: same as Timestamp, may be null
ARRIVAL_PORT_CALC: see ports.csv, may be null

2. Yes, it will be added ASAP. Please find description [here](https://help.marinetraffic.com/hc/en-us/articles/205579997-What-is-the-significance-of-the-AIS-Shiptype-number-)

3. Ports.csv is enought to work with dataset. We already gathered port coordinates and optimal radiuses to the file. So additional information can be avoided.

4. For Q1 it should be <TaskId, PortName>, for Q2 - <TaskId, timestamp>. I will include that to the Readme of the sample system. 

5. No. Queues are different.

**Comment by smirnp** [comment]
@twhuang-uiuc , please find the corrected ranges (over the training+test data) in the comment above.

**Comment by clin99** [comment]
@smirnp ,  for the Ports.csv, how does our system access this file during online testing?  Is the file provided before we upload our system and when will the online benchmark be available?

Thanks.

**Comment by smirnp** [comment]
@clin99, since participants' systems are executing as docker containers, they do not share filesystem with benchmark components. If you plan to use the file inside your system you may add it into docker image of your system. If you are using the SDK-based sample system, you may do that by calling the `addFileOrFolder` method for systemAdapterBuilder, which you may find in the [SampleSystemTest.java](https://github.com/hobbit-project/DEBS-GC-2018/blob/master/src/test/java/org/hobbit/debs_2018_gc_samples/SampleSystemTest.java).

**Comment by micheleporretta** [comment]
Hi! I didn't understand why the description of the shiptype is no longer present on the homepage of the challenge. Has it been removed? In the case, it is a real pity! Shiptype was a very useful information! 

Furthermore, is it possible to know exactly the composition of the final tuple? it is important in order to be able to deserialize correctly.

**Comment by smirnp** [comment]
Hi! 

ShipType is still actual field, the description will be added to the website shortly.

'Composition of the final tuple' - if you mean the format, which should be sent to Evaluation Storage, then you can find it in [here](https://github.com/hobbit-project/DEBS-GC-2018/blob/master/src/main/java/org/hobbit/debs_2018_gc_samples/System/SystemAdapter.java) lines 50-52. If not, then I didn't got the point, please describe it in detail.

**Comment by Abder88** [comment]
is't possible that the timestamp can be greater than the Arrival_CALC ?
0xc35c9ebbf48cbb5857a868ce441824d0b2ff783a;99;5.8;14.51453;35.89511;44;511;**12/03/2015 07:41**;MARSAXLOKK;;**10/03/2015 13:13**;VALLETTA

**Comment by micheleporretta** [comment]
@Abder88 what is the question?

**Comment by smirnp** [comment]
@Abder88, yes. 
Since we calculated arrival timestamps using radiuses from the ports.csv (3-12 km), all the tuples within port circles still remain in the data set. Such tuples should not be considered to be predicted and evaluated, since ship have already arrived to the port. While it is a noise, we decided to leave it as it exists in real system.
