### ISSUE TITLE
Availability of benchmark information and online evaluation

### ISSUE THREAD

**Issue by florianschmidt1994** [hobbit-project/DEBS-GC-2018#12]
Hello everyone,

can you give as an estimation about when the benchmark information for the system.ttl is going to be available and at what point we can test our solutions by uploading them to the hobbit platform?

Thanks!

**Comment by smirnp** [comment]
Hi! Please find the [system.ttl](https://github.com/hobbit-project/DEBS-GC-2018/blob/master/system.ttl). 
For your system you have to modify: 
1. System URI - from the line `<yourSystemURI> a hobbit:SystemInstance`
2. Label and Comment - will be displayed in GUI
3. ImageName: the url at which your docker image was uploaded.

To upload a docker image of your system to the online platform you have to:
1. Create a user account in the [platform](https://master.project-hobbit.eu).
2. Create a new project at platform's [GitLab](https://git.project-hobbit.eu).
3. Modify GIT_REPO_PATH and PROJECT_NAME at [Constants.java](https://github.com/hobbit-project/DEBS-GC-2018/blob/master/src/main/java/org/hobbit/debs_2018_gc_samples/Benchmark/Constants.java) to fit the URL of project you have created.
4. Build docker image using the `buildImages()` from the [SampleSystemTest.java](https://github.com/hobbit-project/DEBS-GC-2018/blob/master/src/test/java/org/hobbit/debs_2018_gc_samples/SampleSystemTest.java). The full URI of build image will be shown in console - should fit the URI of you project you just created. 
5. Login to the remote gitlab from console: `sudo docker login git.project-hobbit.eu:4567`.
6. Push your image to remote gitlab by the `docker push <imageUri>`.
7. Put the modified benchmark.ttl into you project at GitLab (check whether ImageName fits the URI of the image you have just pushed).
8. Find your system in the GUI under the Benchmarks Tab after selecting the DEBS GC 2018 Benchmark. GUI will apply the updated System.ttl within 30-60 seconds after it has been changed.
