### ISSUE TITLE
Interpreting of evaluation log

### ISSUE THREAD

**Issue by nduy** [hobbit-project/DEBS-GC-2018#13]
Hi @smirnp. In the logging, I found some lines like the following
>
2018-03-20 13:03:38,656 DEBUG [org.hobbit.debs_2018_gc_samples.Benchmark.TaskGenerator] - <tuples 44 sent. Curr: 0 tuples/s>
2018-03-20 13:03:39,538 DEBUG [eval-storage-dockerizer] - <2018-03-20 13:03:39,315 DEBUG [org.hobbit.smlbenchmark_v2.benchmark.EvalStorage] - <Expectations: 44 (0 t/s) Actuals: 43 (0 t/s)>
>
2018-03-20 13:03:39,657 DEBUG [org.hobbit.debs_2018_gc_samples.Benchmark.TaskGenerator] - <tuples 44 sent. Curr: 0 tuples/s>
2018-03-20 13:03:40,552 DEBUG [eval-storage-dockerizer] - <2018-03-20 13:03:40,316 DEBUG [org.hobbit.smlbenchmark_v2.benchmark.EvalStorage] - <Expectations: 44 (0 t/s) Actuals: 43 (0 t/s)>

Could you please kindly explain what these number means, especially the  <Expectations: 44 (0 t/s) Actuals: 43 (0 t/s)> tuple. Thanks!

**Comment by smirnp** [comment]
Hi @nduy , this is current status of the evaluation storage at the moment: 
44 expected tuples received from TaskGenerator and 43 responses (predictions) were returned from a system.

The TaskGenerator sends tuples to both: 
- to the benchmarked system - raw data tuple itself
- to the evaluation storage - expected result for each tuple sent for the system

**Comment by nduy** [comment]
So if I understand well, if everything works properly, it should output <Expectations: 44 (0 t/s) Actuals: 44 (0 t/s)>, right? In my case, it keep printing  <Expectations: 44 (0 t/s) Actuals: 43 (0 t/s)>....

**Comment by smirnp** [comment]
Yes, you are right. 
It seems like evalStorage did not received the 44-th prediction from the system and cannot finish the benchmark execution. 
Could you please provide inputs of your execution (queryType, tuplesLimit)?
I have have checked on the modified sample system, which returns 43 tuples, when the whole tuplesLimit=44 and it repeats the problem. If system returns 44 tuples, then everything benchmark is finishing.

**Comment by nduy** [comment]
Thank you @smirnp. Everything is fine now.

**Comment by Abder88** [comment]
so, finally i was able to test my system on the hobbit platform but i can't understand the error bellow, any help ?

[{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/debs-trajectpm:latest","@timestamp":"2018-04-27T14:52:18.322Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76","message":"\tat org.hobbit.core.run.ComponentStarter$1.run(ComponentStarter.java:133)","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHly4a3jXgEFR60_oU","sort":[1524840738322,"other#AWMHly4a3jXgEFR60_oU"],"_score":null},{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/debs-trajectpm:latest","@timestamp":"2018-04-27T14:52:18.322Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76","message":"\tat org.hobbit.core.run.ComponentStarter.access$000(ComponentStarter.java:33)","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHly4a3jXgEFR60_oT","sort":[1524840738322,"other#AWMHly4a3jXgEFR60_oT"],"_score":null},{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/debs-trajectpm:latest","@timestamp":"2018-04-27T14:52:18.321Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76","message":"\tat org.hobbit.core.run.ComponentStarter.closeComponent(ComponentStarter.java:125)","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHly4a3jXgEFR60_oS","sort":[1524840738321,"other#AWMHly4a3jXgEFR60_oS"],"_score":null},{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/debs-trajectpm:latest","@timestamp":"2018-04-27T14:52:18.321Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76","message":"\tat org.apache.commons.io.IOUtils.closeQuietly(IOUtils.java:303)","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHly4a3jXgEFR60_oR","sort":[1524840738321,"other#AWMHly4a3jXgEFR60_oR"],"_score":null},{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/debs-trajectpm:latest","@timestamp":"2018-04-27T14:52:18.319Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76","message":"\tat org.hobbit.debs_2018_gc_samples.System.SystemAdapter.close(SystemAdapter.java:204)","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHly4a3jXgEFR60_oQ","sort":[1524840738319,"other#AWMHly4a3jXgEFR60_oQ"],"_score":null},{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/debs-trajectpm:latest","@timestamp":"2018-04-27T14:52:18.319Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76","message":"Exception in thread \"Thread-0\" java.lang.NullPointerException","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHly4a3jXgEFR60_oP","sort":[1524840738319,"other#AWMHly4a3jXgEFR60_oP"],"_score":null},{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/debs-trajectpm:latest","@timestamp":"2018-04-27T14:52:18.319Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76","message":"\tat org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:72)","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHly4a3jXgEFR60_oO","sort":[1524840738319,"other#AWMHly4a3jXgEFR60_oO"],"_score":null},{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/debs-trajectpm:latest","@timestamp":"2018-04-27T14:52:18.319Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76","message":"\tat org.hobbit.core.run.ComponentStarter.closeComponent(ComponentStarter.java:125)","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHly4a3jXgEFR60_oN","sort":[1524840738319,"other#AWMHly4a3jXgEFR60_oN"],"_score":null},{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/debs-trajectpm:latest","@timestamp":"2018-04-27T14:52:18.319Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76","message":"\tat org.apache.commons.io.IOUtils.closeQuietly(IOUtils.java:303)","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHly4a3jXgEFR60_oM","sort":[1524840738319,"other#AWMHly4a3jXgEFR60_oM"],"_score":null},{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/debs-trajectpm:latest","@timestamp":"2018-04-27T14:52:18.318Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76","message":"\tat org.hobbit.debs_2018_gc_samples.System.SystemAdapter.close(SystemAdapter.java:204)","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHly4a3jXgEFR60_oL","sort":[1524840738318,"other#AWMHly4a3jXgEFR60_oL"],"_score":null},{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/debs-trajectpm:latest","@timestamp":"2018-04-27T14:52:18.318Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76","message":"Exception in thread \"main\" java.lang.NullPointerException","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHly4a3jXgEFR60_oK","sort":[1524840738318,"other#AWMHly4a3jXgEFR60_oK"],"_score":null},{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/debs-trajectpm:latest","@timestamp":"2018-04-27T14:52:18.315Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76","message":"\tat org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:65)","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHly4a3jXgEFR60_oJ","sort":[1524840738315,"other#AWMHly4a3jXgEFR60_oJ"],"_score":null},{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/debs-trajectpm:latest","@timestamp":"2018-04-27T14:52:18.315Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76","message":"\tat org.hobbit.debs_2018_gc_samples.System.SystemAdapter.init(SystemAdapter.java:66)","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHly4a3jXgEFR60_oI","sort":[1524840738315,"other#AWMHly4a3jXgEFR60_oI"],"_score":null},{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/debs-trajectpm:latest","@timestamp":"2018-04-27T14:52:18.315Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76","message":"\tat org.hobbit.sdk.JenaKeyValue$Builder.buildFrom(JenaKeyValue.java:72)","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHly4a3jXgEFR60_oH","sort":[1524840738315,"other#AWMHly4a3jXgEFR60_oH"],"_score":null},{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/dmessage":"java.lang.NullPointerException"ebs-trajectpm:latest","@timestamp":"2018-04-27T14:52:18.315Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76",","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHly4a3jXgEFR60_oG","sort":[1524840738315,"other#AWMHly4a3jXgEFR60_oG"],"_score":null},{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/debs-trajectpm:latest","@timestamp":"2018-04-27T14:52:18.313Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76","message":"2018-04-27 14:52:18,312 ERROR [org.hobbit.core.run.ComponentStarter] - <Exception while executing component. Exiting with error code.>","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHly4a3jXgEFR60_oF","sort":[1524840738313,"other#AWMHly4a3jXgEFR60_oF"],"_score":null},{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/debs-trajectpm:latest","@timestamp":"2018-04-27T14:52:18.309Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76","message":" skipped on port 22011","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHly4K3jXgEFR60_oE","sort":[1524840738309,"other#AWMHly4K3jXgEFR60_oE"],"_score":null},{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/debs-trajectpm:latest","@timestamp":"2018-04-27T14:52:18.308Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76","message":"end of training using 516575 row from 542152execp 3563skipped 0","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHly4K3jXgEFR60_oD","sort":[1524840738308,"other#AWMHly4K3jXgEFR60_oD"],"_score":null},{"_index":"logstash-2018.04.27","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/a.k/debs-trajectpm:latest","@timestamp":"2018-04-27T14:52:09.931Z","container_name":"debs-trajectpm-bf905c88154d40f695230b180c2fd0dd.1.oy2307wipmmc7lc0phf9o5x76","message":"2018-04-27 14:52:09,932 DEBUG [org.hobbit.debs_2018_gc_samples.System.SystemAdapter] - <Init finished>","container_id":"83bdf32869f0797a2441c718970b57f1f0be1a45de49693c28d29ae112683837"},"_id":"AWMHlw1S3jXgEFR60_nz","sort":[1524840729931,"other#AWMHlw1S3jXgEFR60_nz"],"_score":null}]

**Comment by MichaelRoeder** [comment]
Please try to format your log file. It is a JSON object and a lot of editors can show it in a much better structure than a bunch of text :wink: 
Apart from that, it looks like there is a small copy & paste problem because the JSON structure is violated. However, your log looks like
```
2018-04-27 14:52:09,932 DEBUG [org.hobbit.debs_2018_gc_samples.System.SystemAdapter] - <Init finished>
end of training using 516575 row from 542152execp 3563skipped 0
 skipped on port 22011
2018-04-27 14:52:18,312 ERROR [org.hobbit.core.run.ComponentStarter] - <Exception while executing component. Exiting with error code.>
java.lang.NullPointerException
    at org.hobbit.sdk.JenaKeyValue$Builder.buildFrom(JenaKeyValue.java:72)
    at org.hobbit.debs_2018_gc_samples.System.SystemAdapter.init(SystemAdapter.java:66)
    at org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:65)
```
After that exception, there are two other `NullPointerExceptions` causing the main thread and a second thread to terminate. However, I think that the Exception above causes your problem. I assume @smirnp can give you a better hint where the exception came from :wink:
