### ISSUE TITLE
Golden solution?

### ISSUE THREAD

**Issue by clin99** [hobbit-project/DEBS-GC-2018#14]
We have successfully got the local Benchmark up and running. The question is: how do we get the golden solution for each query? We didn't receive any feedback (correct destination and arrival time) from the Benchmark after we send the prediction result. We assume the contest is running in a online fashion as you replied [here](https://github.com/hobbit-project/DEBS-GC-2018/issues/1). 

Thanks!

**Comment by clin99** [comment]
Please let us know how to get the feedback for a query. This is a very important information, or we cannot proceed to the next step.

Thanks!

**Comment by smirnp** [comment]
Hi! Sorry for long answer. 
If you mean a golden solution for offline training (e.g. local) of your algorithm, then you may find it in training dataset. 
If you mean a golden solution during the online benchmarking (at the online platform) - it will not be given to the system/algorithm, as it is considered to be already trained (offline) and ground truth will be used only for results calculation.
