### ISSUE TITLE
Questions about online benchmark

### ISSUE THREAD

**Issue by clin99** [hobbit-project/DEBS-GC-2018#17]
I have three questions about the online benchmark:

1. Which queue (task queue or data queue) is used by the benchmark to send the query to our system?   

2. Should our system connect to both the task queue and data queue or just the task queue?  

3. According to the local benchmark, the output format is "port name, arrival time". Shouldn't we put the task id in the output?

Thanks!

**Comment by smirnp** [comment]
Hi!
 If you create your system in Java, then you may reuse the [SystemAdapter](https://github.com/hobbit-project/DEBS-GC-2018/blob/master/src/main/java/org/hobbit/debs_2018_gc_samples/System/SystemAdapter.java), which implements everything you need to connect the queues and sent results back. You you planning to create a docker image with non java inside, then you may do a reverse engineering of SystemAdapter.java and AbstractSystemAdapter.class (last is a basics of the first) to get the full picture, which functionality have to be implemented (including handling commands from the platform).
1. SystemAdapter listens data from both queues, but benchmark uses only task queue to sent tuples.
2. Connect to the task queue is enough, but your also system have to listen platform commands from command queue.
3. "port name, arrival time" is a format of returning tuple. Of course each tuple is accompanied with taskId, but it does not require user attention if he uses Java example. You may find the logic of accompanying in the AbstractSystemAdapter.class.
