### ISSUE TITLE
Response lost while sending to EvalStorage

### ISSUE THREAD

**Issue by nduy** [hobbit-project/DEBS-GC-2018#18]
I am currently having the issue of timeout (set to 60mins) error due to the fact that Actuals is less than Expectation. So I made a number of tries on your **Original** code. I happed to me that when the `GENERATOR_LIMIT` is small (say 72, 1k or 10k), the issue did not occurs. But when this threshold is set to 100k, it got stuck with the following log until timeout:
> DEBUG [eval-storage-dockerizer] - <2018-03-29 16:55:23,985 DEBUG [org.hobbit.smlbenchmark_v2.benchmark.EvalStorage] - <Expectations: 99753 (0 t/s) Actuals: 99751 (0 t/s)>

I tested on 2 machines, and the above mentioned issue happened in both cases (expectation is always 99753 and actuals is 99751). In the code involving the solution, the issue occurs at earlier tuples. Additionally, I did stop and remove any running containers before starting the new test.

This is my Java and Docer version:

> java version "1.8.0_162"
> Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
> Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

> Docker version 18.03.0-ce, build 0520e24

Could you please reproduce the issue and try to help me solve it? Thank you very much.

**Comment by smirnp** [comment]
I have fixed the bug. Please find the updated Task Generator in the repository.

**Comment by nduy** [comment]
Thank you for your fix. I tested and everything worked well :+1:
