### ISSUE TITLE
Questions about evaluation and query type

### ISSUE THREAD

**Issue by clin99** [hobbit-project/DEBS-GC-2018#19]
Hi, I have several questions regarding the evaluation and online Benchmark: 

1. For the Score A1, will a ship have multiple trips (e.g. A->B and C->D)?   If this is true, how to calculate the Score A1 in such case?

2. Could you give more details on how to calculate the final Score A1?   For example, if there are two trips in total and the predicted sequences are:

Trip 1:
1. Time:01, Predicted Dest: A (Start of Trip)
2. Time:02, Predicted Dest: B
3. Time:03, Predicted Dest: A
4. Time:04, Predicted Dest: B
5. Time:05, Predicted Dest: B
6. Time:06, Predicted Dest: B (Arrival at B)

Trip 2:
1. Time:01, Predicted Dest: C (Start of Trip)
2. Time:02, Predicted Dest: C
3. Time:03, Predicted Dest: C
4. Time:04, Predicted Dest: D
5. Time:05, Predicted Dest: D (Arrival at D)

What is the final Score A1?

3. Which one (`averageLatencyMs` or `systemWorkingTimeSeconds` or other) is used as the total runtime of the system (Rank B1)?  

4. For the online Benchmark, how to let our system know the current query type (Q1 or Q2) during test?

Thanks!

**Comment by smirnp** [comment]
Hi! 
1. TotalScore = Sum(Earlyness rate of each trip)/total number of trips
2. EarlynessRateTrip1 = (Time:06-Time:04)/(Time:06-Time:0.1)
EarlynessRateTrip2 = (Time:05-Time:04)/(Time:05-Time:0.1)
3. SystemWorkingTimeSeconds is used for the total runtime
4. The parameter will be sent by benchmark and parsed during system initialization. See lines 23-26 in [SystemAdapter.java](https://github.com/hobbit-project/DEBS-GC-2018/blob/master/src/main/java/org/hobbit/debs_2018_gc_samples/System/SystemAdapter.java#L26)

**Comment by acip** [comment]
Hi Pavel,

Regarding #2 above, I guess you meant Time:06-Time:04 and Time:05-Time:04

Right?
Thanks!

**Comment by clin99** [comment]
@smirnp  If we don't use the provided SystemAdapter.java, how does our system know the parameter (`QUERY_TYPE`) on the online platform?    Will the Benchmark send the parameter through either data or task queue?       

Thanks.

**Comment by smirnp** [comment]
@acip , yes. Thank you!

**Comment by smirnp** [comment]
@clin99 , the model is sending to a system as an environment variable called `SYSTEM_PARAMETERS_MODEL `

**Comment by clin99** [comment]
@smirnp   I have checked the environment variable `SYSTEM_PARAMETERS_MODEL`, it only contains the container id like this `{","container_id":"c96bd753e7062d34fa8379c56d20588f318a03cdf307862451b3b5d144832313"}`
There is no `queryType`.

**Comment by smirnp** [comment]
By which software you create/run your system container? 
The environment variables (depending on the type of runnable HOBBIT component) should be prior specified by the software, which creates/runs your container. 

In case of SDK the `SYSTEM_PARAMETERS_MODEL` is specified via `setupSystemEnvironmentVariables()` in [SampleSystemTest.java](https://github.com/hobbit-project/DEBS-GC-2018/blob/119a8c6b330df89d64b9277f0f344feff25ced77/src/test/java/org/hobbit/debs_2018_gc_samples/SampleSystemTest.java#L52). Then via [SystemAdapterDockersBulder](https://github.com/hobbit-project/java-sdk/blob/2ca9c2052a5c3e2494ab999855074faa3a411f6f/src/main/java/org/hobbit/sdk/docker/builders/hobbit/SystemAdapterDockerBuilder.java#L39) it is forwarding to the [AbstractDockerizer](https://github.com/hobbit-project/java-sdk/blob/2ca9c2052a5c3e2494ab999855074faa3a411f6f/src/main/java/org/hobbit/sdk/docker/AbstractDockerizer.java#L294), which creates and starts the container.

In case of the HOBBIT platform environment variables are also set up via [ContainerManagerImpl.java](https://github.com/hobbit-project/platform/blob/c7b1e05f956bba66088df946e67350a33202fe7a/platform-controller/src/main/java/org/hobbit/controller/docker/ContainerManagerImpl.java#L372), which created a container and then starts it. So in the online platform the parameters will be specified for your system by the platform itself.

If I'm not mistaken, the environment variables can also be specified in DockerFile or via command line arguments.

**Comment by smirnp** [comment]
This is a part of log file of my DummySystem, which was executed in the online platform. You may find the QueryType the SystemModel in logs (read from bottom to top):

```
2018-04-04 14:58:45,778 DEBUG [org.hobbit.smlbenchmark_v2.system.SystemAdapter] - <Reading data/debs
>","container_id":"7344c7fba6254906a2ac69fddaa75b71601c4c145d79351317a34a7823c69cce"},"_id":"AWKRKtO
}","container_id":"7344c7fba6254906a2ac69fddaa75b71601c4c145d79351317a34a7823c69cce"},"_id":"AWKRKtO
  }","container_id":"7344c7fba6254906a2ac69fddaa75b71601c4c145d79351317a34a7823c69cce"},"_id":"AWKRK
    }","container_id":"7344c7fba6254906a2ac69fddaa75b71601c4c145d79351317a34a7823c69cce"},"_id":"AWK
      \"@id\" : \"http://www.w3.org/2000/01/rdf-schema#label\"","container_id":"7344c7fba6254906a2ac
    \"label\" : {","container_id":"7344c7fba6254906a2ac69fddaa75b71601c4c145d79351317a34a7823c69cce"
    },","container_id":"7344c7fba6254906a2ac69fddaa75b71601c4c145d79351317a34a7823c69cce"},"_id":"AW
      \"@id\" : \"http://www.w3.org/2000/01/rdf-schema#comment\"","container_id":"7344c7fba6254906a2
    \"comment\" : {","container_id":"7344c7fba6254906a2ac69fddaa75b71601c4c145d79351317a34a7823c69cc
    },","container_id":"7344c7fba6254906a2ac69fddaa75b71601c4c145d79351317a34a7823c69cce"},"_id":"AW
      \"@id\" : \"http://w3id.org/hobbit/vocab#imageName\"","container_id":"7344c7fba6254906a2ac69fd
    \"imageName\" : {","container_id":"7344c7fba6254906a2ac69fddaa75b71601c4c145d79351317a34a7823c69
    },","container_id":"7344c7fba6254906a2ac69fddaa75b71601c4c145d79351317a34a7823c69cce"},"_id":"AW
      \"@type\" : \"http://www.w3.org/2001/XMLSchema#int\"","container_id":"7344c7fba6254906a2ac69fd
      \"@id\" : \"http://project-hobbit.eu/sml-benchmark-v2/queryType\",","container_id":"7344c7fba6
    \"queryType\" : {","container_id":"7344c7fba6254906a2ac69fddaa75b71601c4c145d79351317a34a7823c69
  \"@context\" : {","container_id":"7344c7fba6254906a2ac69fddaa75b71601c4c145d79351317a34a7823c69cce
  \"label\" : \"Dummy system2 for SMLv2 (DEBS 2018) benchmark\",","container_id":"7344c7fba6254906a2
  \"comment\" : \"Dummy system2 for SMLv2 (DEBS 2018) benchmark (http://project-hobbit.eu/sml-benchm
  \"imageName\" : \"git.project-hobbit.eu:4567/smirnp/sml-benchmark-v2/system-adapter\",","container
  \"queryType\" : \"2\",","container_id":"7344c7fba6254906a2ac69fddaa75b71601c4c145d79351317a34a7823
  \"@id\" : \"http://jenaKeyValue.com/experimentUri\",","container_id":"7344c7fba6254906a2ac69fddaa7
2018-04-04 14:58:45,775 DEBUG [org.hobbit.smlbenchmark_v2.system.SystemAdapter] - <SystemModel: {
2018-04-04 14:58:45,735 DEBUG [org.hobbit.smlbenchmark_v2.system.SystemAdapter] - <Init()>
2018-04-04 14:58:45,113 DEBUG [Jena] - <Jena initialization>","container_id":"7344c7fba6254906a2ac69
```

**Comment by clin99** [comment]
@smirnp   We did not use the provided Java code, instead we use docker to directly package our system into a container and upload it to the HOBBIT platform. Now if we want to test different query types on the HOBBIT platform, we have to modify the system locally and re-package it into a container and re-upload it.   Is there any way to directly let the system on the HOBBIT platform know the current query type?

**Comment by smirnp** [comment]
@clin99, I have looked into your log file and see queryType there - it outputs as several lines (this is just logs representation).

```
":"  \"implementsAPI\" : \"http://project-hobbit.eu/sml-benchmark-v2/API\",","container_id":"60faa8c4c
":"  \"imageName\" : \"git.project-hobbit.eu:4567/clin99/gc2018\",","container_id":"60faa8c4cb2e45dcf8
":"  \"queryType\" : \"1\",","container_id":"60faa8c4cb2e45dcf8967c232ef70610f28881a4984d0fa7d00b13f45
":"  \"@type\" : \"hobbit:SystemInstance\",","container_id":"60faa8c4cb2e45dcf8967c232ef70610f28881a49
":"  \"@id\" : \"http://project-hobbit.eu/resources/gc2018408/test/debsparrotsystemexample\",","contai
":"AAAAAAAAAAAAAAA   SYSTEM_PARAMETERS_MODEL = {","container_id":"60faa8c4cb2e45dcf8967c232ef70610f288
":"MODEL Ready","container_id":"60faa8c4cb2e45dcf8967c232ef70610f28881a4984d0fa7d00b13f45dcd51da"},"_i
":"Leave COMMAND","container_id":"60faa8c4cb2e45dcf8967c232ef70610f28881a4984d0fa7d00b13f45dcd51da"},"
":"HANDLE CMD","container_id":"60faa8c4cb2e45dcf8967c232ef70610f28881a4984d0fa7d00b13f45dcd51da"},"_id
":"Waiting for CMD","container_id":"60faa8c4cb2e45dcf8967c232ef70610f28881a4984d0fa7d00b13f45dcd51da"}
```

You have to implement parsing of the following model in you code (and get the query type) which arrives as `SYSTEM_PARAMETERS_MODEL` env variable to your system:
 `{
  "@id" : "http://jenaKeyValue.com/URI",
  "queryType" : "2",
  "@context" : {
    "queryType" : {
      "@id" : "http://project-hobbit.eu/sml-benchmark-v2/queryType",
      "@type" : "http://www.w3.org/2001/XMLSchema#int"
    }
  }
}`

**Comment by clin99** [comment]
@smirnp  Thanks for your help!
