### ISSUE TITLE
deadlines

### ISSUE THREAD

**Issue by rimmmmm** [hobbit-project/DEBS-GC-2018#21]
Hi
what are the deadlines?
please correct if am wrong
15th of April for abstract submission (source: http://www.cs.otago.ac.nz/debs2018/calls/gc.html)
and 
15th of May  for participation to the training phase (source: https://github.com/hobbit-project/DEBS-GC-2018)
best,

**Comment by smirnp** [comment]
Hi! 
The 15th of April is a deadline for submission system to the online platform, as well for paper submission   EasyChair.
After the 15th of April new systems cannot be submitted anymore, but already submitted ones may be tuned during the training phase until the 15th of May.

**Comment by acip** [comment]
Pavel,

I may have missed this, could you point to where "training phase" is
explained or detail it? What does it entail?

**Comment by smirnp** [comment]
Ciprian, please find the description [here](https://project-hobbit.eu/structured-machine-learning-benchmark-v2/). Unfortunately the announcement of the online benchmark was not properly communicated via the [twitter post](https://twitter.com/hobbit_project/status/973815999362351104), which was about the challenge in general.

**Comment by nduy** [comment]
Hi @smirnp . Many thanks for the response. Just to ensure that I understood correctly, from now (April 5) until April 15, we can push our code online and registering our system with a name, then run some initial test. Then, between April 15 to May 15, the code will be tested with several different test samples set. And the final execution will take place by May 15.

And as you said that "already submitted ones may be tuned during the training phase until the 15th of May", does it means that we can still push new dockerized image containing new codes to hobbit platform?

**Comment by smirnp** [comment]
Hi @nduy . 

> from now (April 5) until April 15, we can push our code online and registering our system with a name, then run some initial test.

Yes. After the April 15th an ability to register new systems for challenges (the Training and the Final one)  in the online platform will be closed. But you still may continue to update docker images of the registered systems until the 15th of May for better getting better results. Apart of runs performed by participants manually, the systems registered to the Training challenge will be periodically executed by the platform and ranked in the leaderboards. Systems registered to the Final challenge will be benchmarked by the platform once - after the mid of May and results of that benchmark will remain hidden until the DEBS conference. 

Please don't forget about the paper submission deadline - 15th of April.

**Comment by nduy** [comment]
Thank you very much @smirnp. I am just a bit curious about this piece of information about the paper (taken from [here](https://project-hobbit.eu/challenges/debs2018-grand-challenge/)):

> Finally you need to upload a short paper (2 pages, plus optional appendix) about your solution to EasyChair. The paper will be reviewed to assess the merit and originality of your solution. All solutions of sufficient quality will at least get the chance to present a poster on the DEBS conference.

Does it means that the review and assess merely based on the idea of the solution (`merit and originality`) without taking account the result ended up during training phrase from April 15 to May 15?

**Comment by smirnp** [comment]
@nduy , yes. Papers review process is done independently from the leaderboards ranking. But all ranked systems should have a submitted paper with a description of approach/architecture/etc. 
Systems without a submitted paper will not take part in the final ranking.

**Comment by clin99** [comment]
@smirnp   
1. For registration, do we have to register both the training phase and final execution phase before April 15?   

2. For Query 1 and Query 2, should we use the same system for both?   or could we use different systems for each?

3. Is the deadline of paper submission on easychair also at April 15?    If we made changes to the system after submitting the paper, do we need to submit another the paper?

Thanks.

**Comment by smirnp** [comment]
@clin99 ,
1. Yes.
2. It is up to you. You may switch your system by the query-type parameter, or upload another system and register it for the second query in both challenges. In this case please use the similar looking names for them to identify both of them belongs to your team.
3. Hopefully you will have a chance to modify/extend your system description by the camera-ready submission.

**Comment by clin99** [comment]
@smirnp   Two questions about the paper submission:

1. Is the paper submission deadline also April 15? 

2. Could we just submit a draft and update it after April 15?   We might change the underlying algorithms during the training period of the contest. This can be significantly different from the paper we wrote from now.

**Comment by smirnp** [comment]
@clin99 , a deadline extension will be announced this week. Please stay tuned.

**Comment by nduy** [comment]
Will this deadline extension for both registration and paper @smirnp?

**Comment by rimmmmm** [comment]
@smirnp please extend the deadline for system upload on hobbit

**Comment by smirnp** [comment]
The deadlines will be extended for both (paper and system sumbission).

**Comment by tsung-wei-huang** [comment]
Can u also update the deadline on the official website?

**Comment by smirnp** [comment]
The deadlines have been updated.

**Comment by nduy** [comment]
Thank you @smirnp for the update.
I saw on the website saying that Grand challenge solution submission is **May 7th, 2018**. So how about the Training Phase? How long will it be shifted, and how long will it take for the committee to review our 2-page paper after the deadline May 7th, 2018. 

I am wondering this because for those who need a visa to visit New Zealand, according to New Zealand Immigration [website](https://www.immigration.govt.nz/about-us/policy-and-law/how-the-immigration-system-operates/visa-application-process/how-long-it-takes-to-process-your-visa-application) it may take 20-25 for an application to proceed, without taking account the waiting time for the appointment with the embassy.
