### ISSUE TITLE
Exact format for timestamp in query 2 response

### ISSUE THREAD

**Issue by eonica** [hobbit-project/DEBS-GC-2018#26]
Hello,

Could you please confirm the exact format expected by the benchmark for the timestamp string in the query2 response? Is this similar to the format in the training data, e.g., "24-04-15 10:22". And if yes the 1 digit hours are preceded by a 0 or not - "24-04-15 9:58" or "24-04-15 09:58"? (if I'm not wrong I think that in last training data set they're not). 

Thank you,
Emanuel

**Comment by smirnp** [comment]
Hi! 
The incoming date will be parsed by the [following pattern](https://github.com/hobbit-project/DEBS-GC-2018/blob/94b18c78ce39c9df2e9f300d1e238186f3f02b0e/src/main/java/org/hobbit/debs_2018_gc_samples/Constants.java#L22). 
With 0 or not should not impact.
