### ISSUE TITLE
Coordinate format of sample data

### ISSUE THREAD

**Issue by florianschmidt1994** [hobbit-project/DEBS-GC-2018#3]
Which coordinate system are lat / lon specified in? If they are in WGS84 Decimal Degrees, I assume there is a decimal point to be added after two digits?

```
VESSEL_ID;speed;LON;LAT;COURSE;HEADING;TIMESTAMP;departurePortName;Reported_Draught
0x0fe9acdb3675a8a2942fafbd4af61bc37e44c0ec;45;1474895;4066721;197;223;30/5/2015 4:35;SALERNO;88
```

**Comment by smirnp** [comment]
Hi! 
Please find the fixed samples here:
http://hobbitdata.informatik.uni-leipzig.de/DEBS_GC_2018/

**Comment by naqwert85** [comment]
@smirnp Hi! http://hobbitdata.informatik.uni-leipzig.de/DEBS_GC_2018/ cannot be accessed at the moment.

**Comment by MichaelRoeder** [comment]
@naqwert85 the page is back. See #7
