### ISSUE TITLE
Missing experiments/results

### ISSUE THREAD

**Issue by acip** [hobbit-project/DEBS-GC-2018#36]
Hi @smirnp ,

The context: we have some parameters set for the system. Between runs, we have noticed that the system is updated a little bit later probably due to some cache/lag. In order to make sure we run the experiment with the new changed parameters, we have also (multiple times) changed the system's URI and label.

Recently, we have noticed that our system experiments are not saved/reported. Here are some examples:
https://master.project-hobbit.eu/experiments/1525518667343
https://master.project-hobbit.eu/experiments/1525518463087
https://master.project-hobbit.eu/experiments/1525519056988

They do not display the outcome and they cannot be found in results section.

It is weekend, but if you manage to see this, I really hope for a quick turnaround given the deadline.

Thanks a lot for your effort!

**Comment by smirnp** [comment]
Hi @acip ,

It might be because system returns some unexpected results to evaluation storage and benchmark cannot correctly assess them and returns incorrect evaluation to the platform. 

Please provide me the name/url of your system, I will check it. 
In any case register it for the challenge, since it is already in the platform.

**Comment by acip** [comment]
Hi @smirnp,

We had a couple of runs in the meantime and things got stabilized. 

For reference, this is the current URI for the system: http://project-hobbit.eu/resources/gc2018/test/debsparrotsystemexampleq2

Regarding the registration, can you point us to the described procedure for registering? (I may have missed it)

Thank you!

**Comment by smirnp** [comment]
The registration manual described here: https://github.com/hobbit-project/platform/wiki/Participate-in-a-challenge 

Also (in case if you missed) email us for getting the access to the second training set.

**Comment by acip** [comment]
Thanks!

Already got the second training set.

**Comment by smirnp** [comment]
I have checked your system - it fails with the `could not find address ....io` error and because of that benchmark is killed by the platform without any results in GUI.
