### ISSUE TITLE
Final system registration

### ISSUE THREAD

**Issue by eonica** [hobbit-project/DEBS-GC-2018#38]
Hi @smirnp ,

I have a couple questions on the final system submission. Currently on the conference page it is specified that: _If you have an implementation that is ready to participate in the benchmark (required to win the performance award), your solution must be uploaded to the HOBBIT system by the 7th of May (AOE). We will take your latest upload for the final benchmark._

Could you please clarify if there is any other specific step that we need to complete for registering the system for the GC competition - e.g., should we provide you the exact system URI or name and the authors? 

Also, how will be the system linked to the corresponding paper submission? I assume we should at least specify somewhere the corresponding paper title/authors.

Maybe this was clarified before, but just to be sure: will it be possible to tune the system parameters after 7th of May (AOE) deadline? and if yes what is the degree of freedom we have for this (e.g., is it possible to submit an updated version of the system?) and until what date?

Thank you,
Emanuel

**Comment by smirnp** [comment]
Hi Emanuel,

To participate the challenge you need to register your system for the challenge in the platform. 
Please find the description of registration procedure here: https://github.com/hobbit-project/platform/wiki/Participate-in-a-challenge  as well as in readme file in this repo (section `How to register for the online challenge`). 

Of course you may update images your system until final run (end of May).

**Comment by nduy** [comment]
Hi Pavel,
Thank you for the hard work. Do we need to register both DEBS Grand Challenge 2018 Final Execution and DEBS Grand Challenge 2018 Training phase?

On the registration page, I can see there are many systems, and many of them are not mine. Should I check only my system,  or leave all of them checked?

How do we know that the registration is successful? Or can you update the list of registered systems, so we can be sure that no mistake was made.

Wish you a nice week!

Best,

**Comment by smirnp** [comment]
Hi @nduy ,

You have to register at least to the Final Execution. 

The training phase challenge executes systems periodically (on some % of the test data) and ranks them on the online leader boars, so you may assess your system among others before the final run. The final run will be in the end of May with full test dataset and results will be announced at the conference.

Registration is successful if you see your system (checked) in the list of systems. The ability to see other's systems is a bug now, hopefully it will be fixed by a platform team.

**Comment by nduy** [comment]
Many thanks Pavel!

**Comment by smirnp** [comment]
Please find the [answer](https://github.com/hobbit-project/platform/issues/288#issuecomment-387075084), why you see other's systems. 
Make sure that you setup a proper security level for your repo.

**Comment by rimmmmm** [comment]
Hi,
I didn't have much time  to dockerize my system and attach the sources to it,
I've just uploaded my code to my google drive, and added a reference to it in the paper
Do I still have time to work on docker and upload my code to gitlab? 
best
