### ISSUE TITLE
DEBS Grand Challenge 2018 Training phase - update

### ISSUE THREAD

**Issue by acip** [hobbit-project/DEBS-GC-2018#39]
Hi @smirnp ,

When should we expect for the first training phase run/results?

**Comment by smirnp** [comment]
Hi! Unfortunately we still have troubles at the platform side and waiting fixes from the platform team. I will announce here then results will appear.

**Comment by rivetti** [comment]
Hi @smirnp ,

Would it be possible to give us some notice (ie, 12h) before the execution, allowing to push some fixes and optimization before the run?

**Comment by smirnp** [comment]
The logic we are targeted - to perform autonomous execution rounds every N days (will make it 2-3 days). After a round finishes the list of registered systems is flushed by the platform (in order not to rerun the same versions of systems getting the same results in the next round). 
If participant updates his system and wants to update it's results in leaderboard when he have to register  it for the next round (please do not forget to register for both tasks the Training Challenge). 

Recently we faced with problem and list of systems of the Q2 was already flushed, but no results appeared. So we will register and execute the flushed systems again after the problem with the platform will be fixed (hopefully today).

**Comment by rivetti** [comment]
Hi @smirnp,

Is the current visible leader-board correct?
I am a bit confused about the ranking (some top raking system "terminated with an error").
Also, I am not quite sure about the KPI meaning, could you please summarize them?

Thanks

**Comment by smirnp** [comment]
Hi @rivetti! 
Please don't panic - these are first results produced by the platform and they demonstrate that leaderboard is not correctly configured. 
I'm configuring it at the moment as well as modifying (introducing the summarized KPI) KPIs to rank the systems.

**Comment by smirnp** [comment]
Hi all!
The leaderboard configurations was updated. Systems are ranked by A1 and A2 respectively. 
Leader of the Q2 was not updated during the last challenge round (the platform team is handling the bug now), other systems have been updated as expected.
