### ISSUE TITLE
Meaning of "SHIPTYPE" 

### ISSUE THREAD

**Issue by nduy** [hobbit-project/DEBS-GC-2018#4]
Hi guys,
I found in the training data field named "SHIPTYPE" with 27 different integer values.
Can any help me understand what does it mean?
Thanks!

**Comment by smirnp** [comment]
Hi! 
Please find the information [here](https://help.marinetraffic.com/hc/en-us/articles/205579997-What-is-the-significance-of-the-AIS-Shiptype-number-).

**Comment by nduy** [comment]
Thanks! @smirnp

**Comment by nduy** [comment]
Some ships have type 0.0, which is not included in marine traffic ship type specification. Does it mean null (no info was given) or other?

**Comment by smirnp** [comment]
Let's consider this as no information given.
