### ISSUE TITLE
Ranking formula

### ISSUE THREAD

**Issue by acip** [hobbit-project/DEBS-GC-2018#40]
Hi @smirnp,

Regarding the ranking formula, the site mentions: "the total runtime of the system (Rank B1)." For Rank A1 and A2, the position in the list is used. Can you confirm that the Rank B1 is the total runtime or the position in the list sorted by runtime in increasing order?

If the former is valid, the total runtime, this means that the execution time would have much greater weight in the final score.

Thank you!

**Comment by smirnp** [comment]
Hi @acip ,

B1 - is a position of system in a list ranked by working time (less - better). 

Unfortunately the platform does not support lists with more than one ranking KPI at the moment, but I'm checking if we can do something with on that.
