### ISSUE TITLE
Error while logging in to Hobbit with Docker

### ISSUE THREAD

**Issue by nduy** [hobbit-project/DEBS-GC-2018#42]
Hi Pavel. I currently can't login with the following command:
`docker login git.project-hobbit.eu:4567`
After entering log in information, I received error message:
`Error response from daemon: Get https://git.project-hobbit.eu:4567/v2/: x509: certificate has expired or is not yet valid
`
My latest login was just about 12 hours ago, and everything worked fine for the past months. Could you please have a look at this issue?
Thank you!

**Comment by acip** [comment]
We experience the same. The certificate has expired today.


![image](https://user-images.githubusercontent.com/1649442/40280336-2fba0840-5c5a-11e8-90c6-c5a6c07c223e.png)

**Comment by nduy** [comment]
Oh. It seems like the organizers didn't expect that the challenge last this long... Is there anything we can do rather than waiting, @acip?

**Comment by acip** [comment]
He he, good one :)

I could not find a way around it with docker. I guess it will be solved on
Monday, as it's just a simple renew from Let's Encrypt.

**Comment by smirnp** [comment]
Hi! 
Unfortunately it is a platform problem and not correclates with the challenge. It will be solved on Tuesday because of public holiday on Monday.

**Comment by acip** [comment]
It is working now.

**Comment by nduy** [comment]
Working for me too. Thanks @acip  for let me know.
