### ISSUE TITLE
Status and deadline

### ISSUE THREAD

**Issue by acip** [hobbit-project/DEBS-GC-2018#46]
Hi @smirnp ,

Can you:

1. let us know what is the current status of the benchmarks and what is the plan regarding training and final runs?
2. Can you confirm that the deadline for tampering with our systems is 2018-05-31 **AOE**?

Best regards,
Ciprian Amariei

**Comment by smirnp** [comment]
Hi @acip ,

1. Unfortunately the multi threaded benchmark has a bottleneck (I suppose because of non-distributed evaluation storage, which probably degrades under a higher pressure of multiple generators), so the initial non-distributed mode will be used. The platform will automatically start the Final challenge, then I will check if everything was executed. 
2. By the 2018-05-31 AOE all participants accounts will be frozen to prevent system updates (unfortunately GUI will be unavailable too) until the challenge execution will be finished. Then accounts will become unfrozen and every participant may see execution result (own only).

**Comment by acip** [comment]
Makes sense!

Regarding the testing tuples, is it possible to have the larger amount of
tuples available for the non-distributed mode, also?

Thank you!

**Comment by smirnp** [comment]
@acip , try to run the Mt benchmark with number of generators=1, it should work the same as main benchmark, but with training dataset. For local executions you may use sourcecodes of taksGenerator and training dataset instead of online image.

**Comment by acip** [comment]
Hi @smirnp 

Unfortunately the MT benchmark with number of generators =1 crashed, using a simple parrot test. It stopped after approx 15K tuples.

Also, I am seeing that there is a DEBS challenge running using the MT benchmark. Regarding this, you mentioned yesterday that the single threaded benchmark will be used.

What is the current status/decision? (confused)

Thank you!

**Comment by eonica** [comment]
Dear Pavel,

We currently see experiments being run in the platform as part of the challenge using the multi threaded benchmark ( DEBS GC 2018 Multithreading Benchmark (SML v2-mt) ). Could you please confirm again that the benchmark that will be used in the final evaluation is the original non-multithreaded one? ( DEBS GC 2018 Benchmark ). 

After your initial answer we did tests using just the main non-multithreading benchmark. For the mt benchmark our system would be in an unstable state currently. It is important, therefore, to know which of the benchmarks will be used in the final evaluation phase,

Thank you,
Emanuel

**Comment by smirnp** [comment]
Dear all,

At the moment I'm doing performance checking using the MT benchmark in single mode just using bigger dataset (the training one). Then all the problems will be solved - I will 1) freese participants accounts; 2) update the main benchmark images; 3) execute final challenge; 4) unfreese accounts

**Comment by acip** [comment]
Sounds like a plan :)

Please confirm that 1)... 2)... 3)... 4)... will  happen after 31-05-2018 AOE.

**Comment by smirnp** [comment]
I'm not running the Final Challenge yet, because: 
a) not all systems meet the platform's deadline on fullsize dataset; 
b) not all system return the expected amount of responces (return 1-2 less), which leads to benchmark hanging. 
Hopefully tonigth (gmt+0) the challenge will be executed.

**Comment by nduy** [comment]
Thanks @smirnp. Does these 2 issues caused by the system, or there may be platform-related issue?
And could you firmly clarify whether the final challenge will be executed with MT or single generator?
This is important for us to tune our final system.

**Comment by acip** [comment]
@smirnp We were told that the deadline for updating the system is 31-05-2018 AOE, that is UTC -12. This translates to 01-06-2018 12:00 GMT. A hard deadline is important.

Could you let us know until when are we allowed to update the systems? (datetime and timezone)

The papers deadline was AOE timezoned and this is the norm.

Thank you!

**Comment by smirnp** [comment]
@nduy:
1) Poor performance of several systems
2) Might be a RabbitMQ effect, but not 100% sure
Single mode generator will be used.

**Comment by smirnp** [comment]
@acip , at 31-05-2018 23.59 AOE accounts will be freezed.

**Comment by eonica** [comment]
@smirnp 

Dear Pavel,

Thank you for your answers and all the work on this. 
Just to have it crystal clear: I understand that the Final Challenge evaluation will be done **after 31-05-2018 23.59 AOE**, not before, and we are allowed to update our systems until this time (31-05-2018 23.59 AOE). 

Also, as repeatedly asked before, please clarify which benchmark will be used in the Final Challenge: 
**DEBS GC 2018 Benchmark (SML v2)**
or
**DEBS GC 2018 Multithreading Benchmark (SML v2-mt)** (with one generator)?

Thank you,
Emanuel

**Comment by smirnp** [comment]
@eonica ,
DEBS GC 2018 Benchmark (SML v2)

**Comment by smirnp** [comment]
Dear all, almost all the registered systems successfully passed the performance test avainst the required amount of tuples. 
Authors of non-passed systems are notified.

**Comment by smirnp** [comment]
FYI: in case if storage does not received some tuples from system (message missed between TaskGen and System or  between System and Storage) - then taskGen resends it to system again using the same taskId. If storage already has responce but nofitication about it was missed (message between storage and taskGen was missed) then it ignores new responce, but sends new notification taskGen to avoid benchmark handing. Please be prepared to receive 1-2 repeated points.

**Comment by acip** [comment]
Hi everyone,

This is a call to fair-play. Could we limit the system runs to 5-10min? It should be enough even for 350K points.

There are systems that consistently last ~20min.

Thank you all!

**Comment by acip** [comment]
Hi @smirnp , 

The platform looks like it hang up. (we are unable to cancel the current own experiment)

**Comment by rivetti** [comment]
Seems a couple of teams have decided to take the cluster for themselves

**Comment by acip** [comment]
Indeed, there are systems running for 20+ minutes...even 40...

**Comment by nduy** [comment]
Terribly sorry guys. The system hanged with rabbitMQ error. I tried to stop but didn't respond for a while.
So sorry again! Leaving the field to you guys now. Happy experimenting...

**Comment by acip** [comment]
Platform down.

**Comment by smirnp** [comment]
@acip , I have just applied some fixes for MT benchmark. Could you please cancel your last run?

**Comment by acip** [comment]
We are trying, but it does not respond.

"Failed Unable to remove experiment 1527850978628"

**Comment by smirnp** [comment]
Seems that time for debugging is over. 
Please upload the images, which you wish to participate in the Final Run. 
The accounts will be freezed in 15 min.
