### ISSUE TITLE
URI Conflict in benchmark

### ISSUE THREAD

**Issue by acip** [hobbit-project/DEBS-GC-2018#47]
Hi @smirnp,

We are now seeing this (this is new) when selecting the benchmark:

Invalid Systems
http://project-hobbit.eu/sml-benchmark-v2/system-adapter This image has the same URI as Dummy system for SMLv2 (DEBS 2018) benchmark (http://project-hobbit.eu/sml-benchmark-v2/system-adapter) from micheleporretta / shipstream.

Any ideas? Does this affect the benchmark runs?

Thank you!

**Comment by smirnp** [comment]
Hi @acip ,

This is a bug of the GUI, do not affect benchmark runs

**Comment by smirnp** [comment]
Fixed

**Comment by MichaelRoeder** [comment]
FYI: it is not really a bug. It just tells you that somebody else has defined a system with the same URI (which should be avoided). As long as you still can execute the experiment, the warning is just an information for you and won't influence the benchmark run in any way.
