### ISSUE TITLE
Final results

### ISSUE THREAD

**Issue by acip** [hobbit-project/DEBS-GC-2018#48]
Hi @smirnp ,

Do we have the final results? I see that the accounts have been restored access. Also there are results available. Are the results final? Those from around GMT: Friday, June 1, 2018 9:13 PM?

Thank you!

**Comment by smirnp** [comment]
Hi @acip and all!

Final results are not published as leaderboard until the conference, but you (as system owner) may find the results of your system in the results table.

**Comment by acip** [comment]
Perfect!

Thank you, Pavel!

**Comment by rivetti** [comment]
Hi,
I am not sure where I should look for our system results ...
Can someone enlighten me?

Thanks
