### ISSUE TITLE
Arrival Port Prediction

### ISSUE THREAD

**Issue by HyungKun** [hobbit-project/DEBS-GC-2018#49]
I have a question about the arrival prediction of the port.

For ships with the ship id of "0x0b98f267e96f76f14e1525a40df0274066124eb5", it will travel to BARCELONA -> unknown port -> MONACO -> LIVORNO. (Inside the port radius)

In this case, all depart ports are BARCELONA.

I knew that we decided to split this trip. But it did not actually separate.

I am confused that the depart port does not change when entering a port radius of unknown port, MONACO, or LIVORNO.

1) First, what is the prediction for BARCELONA -> unknown port?
2) When going from unknown port to MONACO, is the arrival port predicted by MONACO? 
Or is LIVORNO the correct prediction?

Could you explain more about this algorithm?

**Comment by smirnp** [comment]
Hi! 
Sorry for a long response. 
Tuple groupings into trips, as well as trips splitting was done in terms of labelling (reflected in fields `tripId`, `ARRIVAL_CALC`, `ARRIVAL_PORT_CALC` only). This had no impact on the original data (incl. the `Departure Port` field) sent to the systems.
