### ISSUE TITLE
Requests for the HOBBIT-compatible python implementation example

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/DEBS-GC-2018#5]
Dear participants,

Here you may leave your requests for the HOBBIT-compatible system example in Python. 

The HOBBIT-compatible system example in Java is already uploaded into the repository.

**Comment by nduy** [comment]
Hi @smirnp,
I believe that HOBBIT-compatible system in Python may be convenient for ML fans. Could you please give me more instruction? Thanks.
Best,

**Comment by florianschmidt1994** [comment]
Is there any update on this?

**Comment by GozdeBoztepe** [comment]
Hi,
Can you give the HOBBIT-compatible system example in Python?
Thanks

**Comment by smirnp** [comment]
Hi! I'm currently working on a python example system, which is planned to be finished in couple of days. Hopefully the submission deadlines will be extended and python-based solutions can easily take part in the Challenge. Stay tuned.

**Comment by smirnp** [comment]
Hi! Please find the python implementation [here](https://github.com/hobbit-project/python-sample-system)

How to do local debugging:
1. Clone this (DEBS-GC-2018) repository as well as the python one.
2. Make sure that `checkHealth()` from the DEBS-GC-2018 executes without errors (see instructions in Readme). 
3. Comment the submission of java-based sample system (line ` .systemAdapter(systemAdapter)` in [SampleSystemTestRunner.java](https://github.com/hobbit-project/DEBS-GC-2018/blob/master/src/main/java/org/hobbit/debs_2018_gc_samples/System/SampleSystemTestRunner.java)) and make sure, that `check_health()` test is not finishing anymore (hangs up after taskGenetator ready signal or something like that. This means waiting of system Adapter, which you excluded from the execution by commenting the line.
4. Package the java code (`mvn package -DskipTests=true`)
5. Open python code and modify the paths to jar file in [SystemAdapterTest.py](https://github.com/hobbit-project/python-sample-system/blob/master/src/test/SystemAdapterTest.py). You may also modify the name of the future docker image of your system.
6. Run the SystemAdapterTest.py from your IDE (running under sudo probably might be requred) and you may debug it.

The actions above will run a target benchmark locally and you may debug your system fully the same way, as it is executed in the online platform. But you may test/debug your system without running benchmark if find the procedure too complicated.

The [standard dockerfile-based image building procedure](https://github.com/hobbit-project/platform/wiki/Upload-a-system) will be required to upload a python system into the online platform. Don't forget to register your system for challenge after uploading.

**Comment by i3hruz** [comment]
Greetings and regards

I am formally requesting the formal approval of the Terms of Use associated with the BigDataOcean 2018 DEBS dataset (https://files.dice-research.org/projects/HOBBIT/DEBS_GC_2018/) which I intend to use for research, analysis, etc. It is important for me to fully understand the terms and ensure that I fully comply with the set.

Furthermore, I would like to kindly request the password required to access the files associated with this dataset. I would appreciate your assistance in this regard and look forward to your prompt response.

Thank you for your attention to this request.

Regards
Behrouz Shokri Fumshi
PhD Student in Computer Science
behrouz.shokri@baboliau.ac.ir
