### ISSUE TITLE
hobbit project is down

### ISSUE THREAD

**Issue by naqwert85** [hobbit-project/DEBS-GC-2018#7]
http://master.project-hobbit.eu/ is down. Please update once the link is back up.

**Comment by MichaelRoeder** [comment]
We are facing some network issues in the university which lead to the problem that our servers are not reachable at the moment. We are working on a fix and will let you know as soon as the servers are back.

We apologize for any inconveniences this may cause.

**Comment by smirnp** [comment]
Now everything seems to be fixed. The platform and servers work normally.

**Comment by MichaelRoeder** [comment]
Sry, but we are not completely done. I will close the issue as soon as we ensured the problem has been fixed completely :wink:

**Comment by MichaelRoeder** [comment]
The platform and services are back :smiley:
