### ISSUE TITLE
Similiarity of training and evaluation / test data

### ISSUE THREAD

**Issue by florianschmidt1994** [hobbit-project/DEBS-GC-2018#8]
I've been wondering if you can / want to provide some information on how similar the training data is compared to the test data that the systems get evaluated with? It would be especially interesting would to know whether the ports in the evaluation are restricted to those 20 ports that are provided as training data, or the global list with all ports worldwide?

**Comment by smirnp** [comment]
The test data is also restricted by the provided ports. You can test your solution on some part of test data by running it under the benchmark in the online platform (will be announced in a coupe of weeks).
