### ISSUE TITLE
Training dataset with blank fields

### ISSUE THREAD

**Issue by micheleporretta** [hobbit-project/DEBS-GC-2018#9]
Hi! 
In the last labeled training dataset, pushed on 05/02/2017, there are 3564 tuples without _arrival_cal_ and _arrival_calc_port_. It's an error or missed data?

thanks,
Michele

**Comment by smirnp** [comment]
Hi!
For these tuples the labels cannot be calculated, because these are deviations (e.g. finished very far from the potential port). Such trips will not be taken into account in evaluation.
